
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:./h2/hrbl-db;
  jpa:
    hibernate:
      ddl-auto: update


